name: Plate Recognizer Stream
version: 1.50.0
slug: frigate
description: process camera or video files on-premise.
image: platerecognizer/alpr-stream
init: false
host_network: true
arch:
  - amd64
  - aarch64
options:
  TOKEN: ""
schema:
  TOKEN: "str"