name: Plate Recognizer Stream
version: 1.50.0
slug: platerecognizer
description: process camera or video files on-premise.
image: platerecognizer/alpr-stream
init: false
host_network: true
arch:
  - amd64
  - aarch64
environment:
  TOKEN: ""