name: "Plate Recognizer Stream"
version: "1.6.9"
slug: platerecognizer
description: >-
  "Process camera or video files on-premise."
init: false
host_network: true
arch:
  - amd64
options:
  TOKEN: ""
  LICENSE_KEY: ""
schema:
  TOKEN: password?
  LICENSE_KEY: password?
map:
  - name: data:rw
    target: /user-data